POST http://localhost:3001/api/user
Content-Type: application/json

{
  "name": "Juan",
  "last_name": "Perez",
  "email": "juanito2@email.com",
  "password": "12345678",
  "sql": "SELECT * FROM users",
  "blablabla": "blublublu"
}

###
GET http://localhost:3001/api/user?email=david@email.com&password=12345678
